[[ACCOUNTS]]
address = "rEP7E8cGfx7zVAfnWxYrASBri7kybayr1h"

[[TOKENS]]
issuer = "rEP7E8cGfx7zVAfnWxYrASBri7kybayr1h"
code = "THRIVE"
name = "THRIVE"
desc = "THRIVE Coin rewards users for participating, posting, commenting, and engaging. Earn coins that grow in value, creating passive income. Holders also vote on platform upgrades, shaping the future of the ecosystem."
icon = "https://raw.githubusercontent.com/thrive183/thrive183.github.io/refs/heads/main/thrivecoin.png"

  [[TOKENS.URLS]]
  url = "https://www.thrivetribes.org"
  type = "info"
  title = "Official Website"

  [[TOKENS.URLS]]
  url = "https://b70b06ee-2299-4273-bab2-9d7328d51211.usrfiles.com/ugd/b70b06_89afce1de18b49f78daa1f9574df2450.pdf"
  type = "whitepaper"
  title = "THRIVE Whitepaper"

  [[TOKENS.URLS]]
  url = "https://x.com/thrive_tribes"
  type = "socialmedia"
  title = "X"
